# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build pr
on:
  pull_request:
    branches:
      - '1.16'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Use gradle cache for faster builds
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Clean gradle
        run: ./gradlew clean --no-daemon --max-workers 1
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
      - name: Validate no assets
        run: test ! -d ./src/generated
      - name: Build with Gradle
        run: ./gradlew remapJar
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          path: build/libs/AE2WTLib-**.jar